# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.6-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2018.4.16-0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/db-5.3.28-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2018.0.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/json-c-0.12.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.14.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.2.0-hdf63c60_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libidn11-1.33-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.16-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-7.2.0-hdf63c60_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-5.9-10.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.41-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.34.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/poppler-data-0.4.9-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/proj4-4.9.3-5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.7-0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/util-linux-2.21-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/x264-20131218-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.5-hfc679d8_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freexl-1.0.5-hf837533_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geos-3.6.2-hfc679d8_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.1.4-h470a237_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gmp-6.1.2-hfc679d8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/graphite2-1.3.11-hfc679d8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.2-hfc679d8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9c-h470a237_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.15-h470a237_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2017.0.4-h4c4d0af_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openblas-0.2.19-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.0.2o-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h470a237_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-7.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.8-h470a237_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.2-h470a237_6.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.2.5-hfc679d8_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h470a237_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/boost-cpp-1.67.0-h3a22d5f_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dbus-1.13.0-h3a4f0e9_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.55.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf4-4.2.13-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jasper-1.900.1-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.34-ha92aebf_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpq-9.6.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libprotobuf-3.5.2-hd28b015_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libssh2-1.8.0-h5b517e9_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.0.9-he6b73bb_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h470a237_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.8-h422b904_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nettle-3.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.20.1-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xerces-c-3.2.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.60.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.8.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geotiff-1.4.2-hb54a4aa_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gnutls-3.5.17-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gstreamer-1.8.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kealib-1.4.9-h0bee7d0_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialite-4.3.0a-19.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.3.0-h0e734dc_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-2.7.15-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/backports-1.0-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/backports_abc-0.5-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/bsddb-1.0-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2018.4.16-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cloudpickle-0.5.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dask-core-0.18.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/enum34-1.1.6-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-4.0-hc8c182b_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.12.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/functools32-3.2.3.2-py27_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/futures-3.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gst-plugins-base-1.8.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/joblib-0.12-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kiwisolver-1.0.1-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libdap4-3.19.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libnetcdf-4.6.1-h5e45101_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.13.3-py27ha266831_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.45.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ptyprocess-0.6.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyshp-1.2.12-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2018.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyzmq-17.1.0-py27hae99301_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scandir-1.7-py27h470a237_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/simplegeneric-0.8.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sip-4.18-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/six-1.11.0-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/subprocess32-3.5.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/toolz-0.9.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.shutil_get_terminal_size-1.0.0-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/boost-1.67.0-py27h3e44d54_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.14.10-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/opencv-2.4.13-np113py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pathlib2-2.3.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pexpect-4.6.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-5.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyproj-1.9.5.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.7.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pywavelets-0.5.2-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/qt-5.6.2-7.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/scipy-0.19.1-np113py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-40.0.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/singledispatch-3.4.0.3-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traitlets-4.3.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/weave-0.15.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.5-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/harfbuzz-1.7.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/imageio-2.3.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_core-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libkml-1.3.0-hfce3912_7.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/networkx-2.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-0.23.3-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pickleshare-0.7.4-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/poppler-0.61.1-3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyqt-5.6.0-py27h8210e8a_6.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/scikit-learn-0.18.1-np113py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-5.0.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wheel-0.31.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-5.2.3-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgdal-2.3.1-ha6e4b24_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libopencv-3.4.1-h1a3b859_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-2.2.2-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-9.0.3-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/prompt_toolkit-1.0.15-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/basemap-1.1.0-py27_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gdal-2.3.1-py27hb00a9d7_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipython-5.7.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/py-opencv-3.4.1-py27h0676e08_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scikit-image-0.14.0-py27hfc679d8_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/basemap-data-hires-1.1.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipykernel-4.8.2-py27_0.tar.bz2
